"""
Django settings for sistema_buap_api project.

Generated by 'django-admin startproject' using Django 2.2.
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# En producción lee la clave de entorno; en local usa la vieja como respaldo
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "-_&+lsebec(whhw!%n@ww&1j=4-^j_if9x8$q778+99oz&!ms2",
)

# DEBUG controlado por variable de entorno (en Render pon DEBUG=False)
DEBUG = os.environ.get("DEBUG", "False") == "True"

# Hosts permitidos (local + Render)
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "sistema-buap-api.onrender.com",  # dominio de tu servicio en Render
]

# Importante para peticiones desde front (CSRF)
CSRF_TRUSTED_ORIGINS = [
    "https://sistema-buap-api.onrender.com",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_auth",
    "corsheaders",
    "sistema_buap_api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS debe ir antes de CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Por ahora dejas CORS abierto para que funcione con cualquier front
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = [
    "http://localhost:4200",
]
CORS_ORIGIN_REGEX_WHITELIST = [
    "http://localhost:4200",
]

ROOT_URLCONF = "sistema_buap_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sistema_buap_api.wsgi.application"


def read_mysql_config():
    """Lee la configuración de MySQL desde my.cnf (para uso local)"""
    config = {}
    config_path = os.path.join(BASE_DIR, "my.cnf")

    if os.path.exists(config_path):
        with open(config_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    key = key.strip()
                    value = value.strip()
                    if key in ["host", "port", "database", "user", "password"]:
                        config[key] = value
    return config


mysql_config = read_mysql_config()

# Primero intenta leer de variables de entorno (Render/Railway),
# si no existen usa lo del my.cnf (para correr en tu máquina)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", mysql_config.get("database", "app_movil_escolar_db")),
        "USER": os.environ.get("DB_USER", mysql_config.get("user", "root")),
        "PASSWORD": os.environ.get("DB_PASSWORD", mysql_config.get("password", "")),
        "HOST": os.environ.get("DB_HOST", mysql_config.get("host", "127.0.0.1")),
        "PORT": os.environ.get("DB_PORT", mysql_config.get("port", "3306")),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Si llegas a manejar media:
# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "sistema_buap_api.models.BearerTokenAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
}

LOGS_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
