# Generated by Django 5.0.2 on 2024-10-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0004_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias',
            new_name='materias_json',
        ),
    ]
