# Generated by Django 5.0.2 on 2024-12-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0005_rename_materias_maestros_materias_json'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Curso', 'Curso'), ('Congreso', 'Congreso'), ('Simposio', 'Simposio'), ('Foro', 'Foro'), ('Otro', 'Otro')], max_length=50)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.CharField(max_length=10)),
                ('hora_fin', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Profesores', 'Profesores'), ('Público general', 'Público general')], max_length=50)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_breve', models.TextField()),
                ('cupo_maximo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsable', to='auth.user')),
            ],
        ),
    ]

